name: fazzah_user
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  easy_localization: ^3.0.3
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_nav_bar: ^5.0.6
  navbar_router: ^0.7.1
  supabase_flutter: ^2.0.1
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.5
  flutter_holo_date_picker: ^1.1.3
  cached_network_image: ^3.3.0
  timer_button: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - .env
  fonts:
    - family: SF-Arabic
      fonts:
        - asset: assets/fonts/SF-Arabic.ttf

